# Generated by Django 4.0.2 on 2022-02-12 14:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocomment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='photocomment',
            old_name='author',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='photocomment',
            old_name='post_date',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='photocomment',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.photo'),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='content',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.photo'),
        ),
    ]
